#!/usr/bin/env bash
#
# Deploy the component harness + dataset to the test box, so the components can be opened
# on a phone, a tablet, or the counter PC rather than only on the machine that built them.
#
#   bun run deploy              source + dataset if it changed, then restart
#   bun run deploy -- --no-db   skip the 137 MB dataset (source-only, much faster)
#   bun run deploy -- --db-only push just the dataset after a regeneration
#
# Run FROM the dev machine. This differs from aph2-diary's update-diary.sh, which runs on
# the target and pulls from git — and it differs for one reason: **the dataset is not in
# git and never will be**. It is 137 MB, generated by datagenerator2, and gitignored. A
# git-pull deploy cannot fetch it, so the source has to be pushed anyway; once you are
# pushing, pushing uncommitted work as well is free. That matters for a test harness, where
# the whole point is trying something on a real device before deciding it is worth keeping.
#
# Everything here is idempotent. First run installs the unit and creates the directories;
# later runs just sync and restart.

set -euo pipefail

TARGET="${MERCHANT_DEPLOY_TARGET:-rcollins@nuc2023}"
APP="${MERCHANT_DEPLOY_PATH:-/opt/rm-merchant-components}"
PORT="${MERCHANT_DEPLOY_PORT:-8788}"
SERVICE=rm-merchant-components
ENV_FILE="/etc/${SERVICE}.env"
REMOTE_DB="${APP}/data/datagenerator.db"

WITH_DB=1
WITH_SOURCE=1
for arg in "$@"; do
  case "$arg" in
    --no-db)   WITH_DB=0 ;;
    --db-only) WITH_SOURCE=0 ;;
    -h|--help) sed -n '2,18p' "$0" | sed 's/^# \{0,1\}//'; exit 0 ;;
    *) echo "unknown option: $arg (try --help)" >&2; exit 2 ;;
  esac
done

cd "$(dirname "$0")/.."
REPO="$PWD"

say() { printf '\n==> %s\n' "$*"; }
step() { printf -- '--> %s\n' "$*"; }

# --- pre-flight, locally --------------------------------------------------------------
#
# Deploying a harness that does not start wastes a round trip and, worse, leaves the box
# serving the previous version while you debug the wrong thing.

say "Pre-flight"
step "Tests"
bun test >/dev/null 2>&1 || { echo "!!! tests fail — not deploying"; exit 1; }
step "Client entry points bundle"
bun run check >/dev/null 2>&1 || { echo "!!! bun run check fails — not deploying"; exit 1; }

# Ask db.js where the dataset is rather than duplicating its resolution order here. It reads
# datagenerator2's own config, so this follows a change to sqlite_path without being told.
LOCAL_DB="$(bun -e 'const m = await import("./server/db.js"); console.log(m.dbPath)' 2>/dev/null | tail -1)"
if [[ $WITH_DB == 1 && ! -f "$LOCAL_DB" ]]; then
  echo "!!! no dataset at ${LOCAL_DB} — generate it, or deploy with --no-db"; exit 1
fi
step "Dataset  ${LOCAL_DB}  ($(du -h "$LOCAL_DB" | cut -f1))"

step "Reachable: ${TARGET}"
ssh -o ConnectTimeout=8 -o BatchMode=yes "$TARGET" true 2>/dev/null \
  || { echo "!!! cannot ssh to ${TARGET} without a password — check ~/.ssh/config and keys"; exit 1; }

# --- make sure the target can hold it -------------------------------------------------

say "Preparing ${TARGET}:${APP}"
# One ssh, one sudo prompt. -t because sudo may want a password on a TTY.
ssh -t "$TARGET" "
  set -euo pipefail

  # Resolve bun rather than assume where it lives. The unit has to name an absolute path —
  # systemd does not search PATH — and guessing wrong gives a service that installs cleanly
  # and then refuses to start. It is /usr/local/bin/bun on the diary boxes and
  # ~/.bun/bin/bun on the dev machine, so it is genuinely not a constant.
  BUN=\$(command -v bun || true)
  if [ -z \"\$BUN\" ]; then echo '!!! bun is not on PATH on this box'; exit 1; fi
  echo \"--> bun at \$BUN\"

  # Is anything already on the port? No sudo: ss without privileges still reports the port
  # as occupied, and 'is it ours' is answered by systemd rather than by parsing process
  # names. The earlier version asked sudo for the process name, and when sudo needed a
  # password it returned nothing and read as 'port free' — a false clear, which is the one
  # answer a preflight must never give.
  if ss -ltnH \"sport = :${PORT}\" 2>/dev/null | grep -q .; then
    if ! systemctl is-active --quiet ${SERVICE} 2>/dev/null; then
      echo \"!!! port ${PORT} on \$(hostname) is in use by something that is not this harness.\"
      echo '    sudo ss -ltnp | grep :${PORT}     # to see what'
      echo '    MERCHANT_DEPLOY_PORT=8790 bun run deploy   # or move out of its way'
      exit 1
    fi
  fi

  sudo mkdir -p '${APP}/data' /var/log/${SERVICE}
  sudo chown -R \$(id -un):\$(id -gn) '${APP}' /var/log/${SERVICE}
"

# --- push ------------------------------------------------------------------------------

if [[ $WITH_SOURCE == 1 ]]; then
  say "Syncing source"
  # --delete so a file removed here disappears there; without it the target accumulates
  # components that no longer exist and the registry disagrees with the directory.
  # data/ is excluded and handled separately — it holds the dataset, which --delete would
  # otherwise remove on every source-only deploy.
  rsync -az --delete \
    --exclude '.git/' --exclude 'node_modules/' --exclude 'data/' \
    --exclude '*.log' --exclude '.env*' \
    --exclude 'src/styles/tailwind.css' --exclude 'src/styles/tailwind.css.js' \
    --exclude 'client/vendor/' \
    "$REPO/" "$TARGET:$APP/"
fi

if [[ $WITH_DB == 1 ]]; then
  say "Syncing dataset (137 MB — only what differs goes over the wire)"
  # -c compares checksums rather than size+mtime. A regenerated SQLite file usually keeps a
  # similar size, and rsync's default heuristic would still send it; the delta algorithm is
  # what makes a re-push of a mostly-unchanged dataset quick.
  rsync -az --info=progress2 -c "$LOCAL_DB" "$TARGET:$REMOTE_DB"
fi

# --- install, build, restart -----------------------------------------------------------

say "Installing and restarting"
ssh -t "$TARGET" "
  set -euo pipefail
  cd '${APP}'

  echo '--> Dependencies'
  bun install --frozen-lockfile >/dev/null

  echo '--> Building client'
  # Generated output (Tailwind CSS + the vendored Lit bundle) is gitignored and excluded
  # from the rsync, so it is built here rather than shipped.
  bun run build >/dev/null

  echo '--> Environment'
  # MERCHANT_DB_PATH is set explicitly even though db.js would find ./data/datagenerator.db
  # by its own fourth rule. Explicit means the startup banner names it, so a wrong dataset
  # is visible in the logs rather than inferred.
  #
  # NODE_ENV is deliberately NOT set to production. isDev gates the query plans, timings and
  # plan warnings that every API envelope carries, and those are the harness — deploying it
  # in production mode would ship the thing with its instruments removed. This is a test box
  # on a home network, not a public service.
  printf 'PORT=%s\nMERCHANT_DB_PATH=%s\n' '${PORT}' '${REMOTE_DB}' \
    | sudo tee '${ENV_FILE}' >/dev/null

  echo '--> Service'
  # ExecStart is rewritten with the bun this box actually has. The committed unit carries the
  # common path as documentation; the installed one carries the true one.
  BUN=\$(command -v bun)
  sed \"s|^ExecStart=.*|ExecStart=\$BUN server/index.js|\" deploy/${SERVICE}.service \
    | sudo tee /etc/systemd/system/${SERVICE}.service >/dev/null
  sudo systemctl daemon-reload
  sudo systemctl enable ${SERVICE} >/dev/null 2>&1 || true
  sudo systemctl restart ${SERVICE}
"

# --- prove it -------------------------------------------------------------------------
#
# systemd reports active as soon as the process starts, which is before Bun binds a
# listener. An immediate check would pass on a server that then dies.

say "Health check"
sleep 3
if DATASET=$(ssh "$TARGET" "curl -fsS -m 10 http://127.0.0.1:${PORT}/api/harness/dataset"); then
  # Parsed with bun rather than grep+cut. The shell version needed escaped quotes inside a
  # command substitution inside a double-quoted string, which silently produced an empty
  # dataset line and a `cut: the delimiter must be a single character` on a deploy that had
  # otherwise worked perfectly.
  echo "$DATASET" | bun -e '
    const d = JSON.parse(await Bun.stdin.text());
    console.log(`    dataset  ${d.dbPath}`);
    console.log(`    source   ${d.dbSource ?? "?"}`);
    const c = d.counts ?? {};
    console.log(`    data     ${c.branch ?? "?"} branches · ${(c.product ?? 0).toLocaleString("en-GB")} products · ${(c.customer ?? 0).toLocaleString("en-GB")} customers`);
  ' 2>/dev/null || echo "    (served, but the dataset endpoint did not parse)"
  HOST=${TARGET#*@}
  say "OK — harness answering on ${HOST}:${PORT}"
  echo "    From another device on the network:  http://${HOST}:${PORT}/"
  echo "    Feature finder:                      http://${HOST}:${PORT}/features"
else
  echo "!!! No answer on ${TARGET}:${PORT}. Logs:"
  echo "    ssh ${TARGET} 'sudo journalctl -u ${SERVICE} -n 50 --no-pager'"
  echo "    ssh ${TARGET} 'tail -30 /var/log/${SERVICE}/stderr.log'"
  exit 1
fi
