// scripts/build-css.js — one Tailwind build, two artifacts (docs/plan.md §5).
//
//   src/styles/tailwind.css      light DOM — linked by the harness pages
//   src/styles/tailwind.css.js   shadow DOM — a CSSResult adopted by every component
//
// Tailwind v4 already emits `:root, :host` for theme variables and `html, :host` for
// preflight, so the shadow artifact needs no rewriting today. hostify() stays as an
// idempotent guard: if a future Tailwind version emits a `:root`-only rule, theme
// variables would silently vanish inside every shadow root, and that failure is very
// hard to read backwards from the symptom.
//
//   bun run css          build once
//   bun run css:watch    rebuild on component/harness/entry changes

import { watch } from "node:fs";
import { existsSync } from "node:fs";

const ENTRY = "src/styles/tailwind.entry.css";
const CSS_OUT = "src/styles/tailwind.css";
const JS_OUT = "src/styles/tailwind.css.js";

// Add :host alongside any bare :root so theme variables survive the shadow boundary.
function hostify(css) {
  return css.replace(/(^|[},]\s*):root(?!\s*,\s*:host)\b/g, "$1:root, :host");
}

async function build() {
  const started = performance.now();
  const proc = Bun.spawn(["bunx", "@tailwindcss/cli", "-i", ENTRY, "-o", CSS_OUT], {
    stdout: "pipe",
    stderr: "pipe",
  });
  const code = await proc.exited;
  if (code !== 0) {
    console.error(await new Response(proc.stderr).text());
    throw new Error(`tailwind cli exited ${code}`);
  }

  const css = await Bun.file(CSS_OUT).text();
  const shadowCss = hostify(css);

  const rewritten = shadowCss !== css;
  await Bun.write(
    JS_OUT,
    `// GENERATED by scripts/build-css.js — do not edit, and do not commit (.gitignore).\n` +
      `// Source: ${ENTRY}\n` +
      `import { unsafeCSS } from "lit";\n\n` +
      `export const tw = unsafeCSS(${JSON.stringify(shadowCss)});\n` +
      `export default tw;\n`,
  );

  const kb = (shadowCss.length / 1024).toFixed(1);
  const ms = Math.round(performance.now() - started);
  console.log(
    `css  ${kb}kB  ${ms}ms` + (rewritten ? "  (applied :root → :root, :host guard)" : ""),
  );
}

if (!existsSync(ENTRY)) throw new Error(`missing ${ENTRY}`);

await build();

if (process.argv.includes("--watch")) {
  console.log("css  watching src/components, client, src/styles/tailwind.entry.css");
  let timer = null;
  const rebuild = () => {
    clearTimeout(timer);
    timer = setTimeout(() => build().catch((e) => console.error(e.message)), 80);
  };
  for (const dir of ["src/components", "client", "src/styles"]) {
    if (existsSync(dir)) watch(dir, { recursive: true }, (_e, name) => {
      // Ignore our own output, or the watcher loops forever.
      if (name && (name.endsWith("tailwind.css") || name.endsWith("tailwind.css.js"))) return;
      rebuild();
    });
  }
}
